name: Dev Workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [features/*, fixes/*]

jobs:
  call-common-deploy:
    uses: ./.github/workflows/common-deploy.yml
    with:
      node-version: "20" # or your required Node.js version
    secrets: inherit
