name: Stage Workflow

on:
  workflow_dispatch:

jobs:
  merge-dev-to-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage branch
        uses: actions/checkout@v4
        with:
          ref: stage
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Patricia"
          git config user.email "patyfb04@gmail.com"

      - name: Fetch all branches
        run: |
          git fetch origin dev
          git fetch origin stage

      - name: Merge dev into stage
        run: |
          git merge origin/dev --no-ff -m "Merge dev into stage [$(date)]"
          git push origin stage

  call-common-deploy:
    needs: merge-dev-to-stage
    uses: ./.github/workflows/common-deploy.yml
    with:
      bun-version: "latest"
