name: Stage Workflow

on:
  workflow_dispatch:

jobs:
  merge-dev-into-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage branch
        uses: actions/checkout@v4
        with:
          ref: stage

      - name: Configure Git
        run: |
          git config user.name "Patricia"
          git config user.email "patyfb04@gmail.com"

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Set up Git authentication
        run: git config --global url."https://${{ secrets.ACTIONS_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Merge dev into stage
        run: |
          git merge origin/dev --no-ff -m "Merge dev into stage"
          git push origin stage

  call-common-deploy:
    needs: merge-dev-into-stage
    uses: ./.github/workflows/common-deploy.yml
    with:
      node-version: "20" # or your required Node.js version
    secrets: inherit
