name: Stage Workflow

on:
  workflow_dispatch:

permissions:
  contents: write # Allow writing to repository
  actions: read # Allow reading actions

jobs:
  merge-dev-to-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage branch
        uses: actions/checkout@v4
        with:
          ref: stage
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "Patricia"
          git config user.email "patyfb04@gmail.com"

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Merge dev into stage
        run: |
          git merge origin/dev --no-ff -m "Merge dev into stage [$(date)]"
          git push origin stage

  call-common-deploy:
    needs: merge-dev-to-stage
    uses: ./.github/workflows/common-deploy.yml
    with:
      bun-version: "latest"
